In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")


In [ ]:
df = pd.read_csv('insurance.csv')

In [ ]:
df.isnull().sum().sort_values(ascending= False)


age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df['sex'] = pd.factorize(df['sex'])[0] + 1
df['region'] = pd.factorize(df['region'])[0] + 1
df['smoker'] = pd.factorize(df['smoker'])[0] + 1
corr = df.corr()
corr['charges'].sort_values(ascending=False)

charges     1.000000
age         0.299008
bmi         0.198341
children    0.067998
sex         0.057292
region      0.006208
smoker     -0.787251
Name: charges, dtype: float64

In [ ]:
X = df.drop('charges', axis = 1)
y = df['charges']
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=101)

In [ ]:
scaler= StandardScaler()
scaler.fit(X_train)
X_train_scaled= scaler.transform(X_train)
X_test_scaled= scaler.transform(X_test)

# Linear Regression

In [ ]:
linear_reg_model= LinearRegression()
linear_reg_model.fit(X_train_scaled, y_train)

LinearRegression()

In [ ]:
y_pred = linear_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)
MAE_li_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_li_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_li_reg =np.sqrt(MSE_li_reg)
pd.DataFrame([MAE_li_reg, MSE_li_reg, RMSE_li_reg], index=['MAE_li_reg', 'MSE_li_reg', 'RMSE_li_reg'], columns=['Metrics'])

Metrics
MAE_li_reg   3.990250e+03
MSE_li_reg   3.353013e+07
RMSE_li_reg  5.790521e+03

In [ ]:
scores = cross_val_score(linear_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.88791389 0.85653048 0.84404195 0.87198372 0.84417492]


# Gradient Boost



In [ ]:
Gradient_model = GradientBoostingRegressor()
Gradient_model.fit(X_train_scaled, y_train)

GradientBoostingRegressor()

In [ ]:
y_pred = Gradient_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)
MAE_gradient= metrics.mean_absolute_error(y_test, y_pred)
MSE_gradient = metrics.mean_squared_error(y_test, y_pred)
RMSE_gradient =np.sqrt(MSE_gradient)
pd.DataFrame([MAE_gradient, MSE_gradient, RMSE_gradient], index=['MAE_gradient', 'MSE_gradient', 'RMSE_gradient'], columns=['Metrics'])

Metrics
MAE_gradient   2.526184e+03
MSE_gradient   2.110072e+07
RMSE_gradient  4.593552e+03

In [ ]:
scores = cross_val_score(Gradient_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.9459288  0.9145374  0.91686777 0.9245836  0.91745967]


# XGBoost Regression

In [ ]:
XGB_model =XGBRegressor()
XGB_model.fit(X_train_scaled, y_train);

In [ ]:
y_pred = XGB_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)
MAE_XGB= metrics.mean_absolute_error(y_test, y_pred)
MSE_XGB = metrics.mean_squared_error(y_test, y_pred)
RMSE_XGB =np.sqrt(MSE_XGB)
pd.DataFrame([MAE_XGB, MSE_XGB, RMSE_XGB], index=['MAE_XGB', 'MSE_XGB', 'RMSE_XGB'], columns=['Metrics'])

Metrics
MAE_XGB   3.142590e+03
MSE_XGB   2.976529e+07
RMSE_XGB  5.455757e+03

In [ ]:
scores = cross_val_score(XGB_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.91782241 0.88730325 0.90410079 0.90440364 0.88383429]


# Decision Tree Regressor

In [ ]:
tree_reg_model =DecisionTreeRegressor()
tree_reg_model.fit(X_train_scaled, y_train);

In [ ]:
y_pred = tree_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)
MAE_tree_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_tree_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_tree_reg =np.sqrt(MSE_tree_reg)
pd.DataFrame([MAE_tree_reg, MSE_tree_reg, RMSE_tree_reg], index=['MAE_tree_reg', 'MSE_tree_reg', 'RMSE_tree_reg'], columns=['Metrics'])

Metrics
MAE_tree_reg   3.533160e+03
MSE_tree_reg   5.026385e+07
RMSE_tree_reg  7.089700e+03

In [ ]:
scores = cross_val_score(tree_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.84365571 0.79897329 0.85711102 0.85617752 0.84559314]


In [ ]:
r2_score(y_test, tree_reg_model.predict(X_test_scaled))


0.6421920507336811

# Random Forest Regressor

In [ ]:
forest_reg_model =RandomForestRegressor()
forest_reg_model.fit(X_train_scaled, y_train);

In [ ]:
y_pred = forest_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)
MAE_forest_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_forest_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_forest_reg =np.sqrt(MSE_forest_reg)
pd.DataFrame([MAE_forest_reg, MSE_forest_reg, RMSE_forest_reg], index=['MAE_forest_reg', 'MSE_forest_reg', 'RMSE_forest_reg'], columns=['Metrics'])

Metrics
MAE_forest_reg   2.881751e+03
MSE_forest_reg   2.555463e+07
RMSE_forest_reg  5.055158e+03

In [ ]:
scores = cross_val_score(forest_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.94269486 0.90634129 0.92126266 0.91531059 0.90681894]


In [ ]:
r2_score(y_test, forest_reg_model.predict(X_test_scaled))


0.8180869768973499

# SVM Regressor

In [ ]:
 from sklearn.svm import SVR


In [ ]:
svm_reg_model =SVR()
svm_reg_model.fit(X_train_scaled, y_train);

In [ ]:
y_pred = svm_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)
MAE_svm_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_svm_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_svm_reg =np.sqrt(MSE_svm_reg)
pd.DataFrame([MAE_svm_reg, MSE_svm_reg, RMSE_svm_reg], index=['MAE_svm_reg', 'MSE_svm_reg', 'RMSE_svm_reg'], columns=['Metrics'])

Metrics
MAE_svm_reg   7.850719e+03
MSE_svm_reg   1.514009e+08
RMSE_svm_reg  1.230451e+04

In [ ]:
scores = cross_val_score(svm_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[nan nan nan nan nan]


In [ ]:
r2_score(y_test, svm_reg_model.predict(X_test_scaled))


-0.07776159498069157

In [ ]:

svm_reg_model = SVR()
svm_reg_model.fit(X_train_scaled, y_train)


SVR()

In [ ]:
y_pred = svm_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_svm_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_svm_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_svm_reg =np.sqrt(MSE_svm_reg)
pd.DataFrame([MAE_svm_reg, MSE_svm_reg, RMSE_svm_reg], index=['MAE_svm_reg', 'MSE_svm_reg', 'RMSE_svm_reg'], columns=['Metrics'])

Metrics
MAE_svm_reg   7.850719e+03
MSE_svm_reg   1.514009e+08
RMSE_svm_reg  1.230451e+04

In [ ]:
scores = cross_val_score(svm_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[nan nan nan nan nan]


In [ ]:

import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error')

model.fit(X_train_scaled, y_train, epochs=100)


Epoch 1/100
30/30 [==============================] - 3s 9ms/step - loss: 330273920.0000
Epoch 2/100
30/30 [==============================] - 0s 10ms/step - loss: 330190048.0000
Epoch 3/100
30/30 [==============================] - 0s 6ms/step - loss: 329999680.0000
Epoch 4/100
30/30 [==============================] - 0s 10ms/step - loss: 329600288.0000
Epoch 5/100
30/30 [==============================] - 0s 9ms/step - loss: 328876640.0000
Epoch 6/100
30/30 [==============================] - 0s 8ms/step - loss: 327681856.0000
Epoch 7/100
30/30 [==============================] - 0s 10ms/step - loss: 325875168.0000
Epoch 8/100
30/30 [==============================] - 0s 11ms/step - loss: 323338240.0000
Epoch 9/100
30/30 [==============================] - 0s 14ms/step - loss: 319906208.0000
Epoch 10/100
30/30 [==============================] - 0s 14ms/step - loss: 315509664.0000
Epoch 11/100
30/30 [==============================] - 0s 12ms/step - loss: 309876192.0000
Epoch 12/100
30/30 [===

In [ ]:
y_pred = model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

13/13 [==============================] - 0s 2ms/step


In [ ]:
!pip install tensorflow-addons

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.8/611.8 kB 7.6 MB/s eta 0:00:00


In [ ]:
scores = cross_val_score(keras.wrappers.scikit_learn.KerasClassifier(model), X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

AttributeError: module 'keras.api._v2.keras' has no attribute 'wrappers'

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
import numpy as np
import pandas as pd

mlp_reg_model = MLPRegressor(random_state=42)

mlp_reg_model.fit(X_train_scaled, y_train)

y_pred_mlp = mlp_reg_model.predict(X_test_scaled)

MAE_mlp_reg = mean_absolute_error(y_test, y_pred_mlp)
MSE_mlp_reg = mean_squared_error(y_test, y_pred_mlp)
RMSE_mlp_reg = np.sqrt(MSE_mlp_reg)

metrics_mlp_reg = pd.DataFrame([MAE_mlp_reg, MSE_mlp_reg, RMSE_mlp_reg],
                               index=['MAE_mlp_reg', 'MSE_mlp_reg', 'RMSE_mlp_reg'],
                               columns=['Metrics'])

print(metrics_mlp_reg)

scores_mlp_reg = cross_val_score(mlp_reg_model, X_train_scaled, y_train, cv=5, scoring='neg_mean_squared_error')
print(np.sqrt(-scores_mlp_reg))

r2_mlp_reg = r2_score(y_test, y_pred_mlp)
print("R-squared score:", r2_mlp_reg)


                   Metrics
MAE_mlp_reg   1.255025e+04
MSE_mlp_reg   2.938602e+08
RMSE_mlp_reg  1.714235e+04
[17168.84474787 17041.67077343 19370.50183615 18396.6791381
 17746.7079636 ]
R-squared score: -1.0918717945708512


In [ ]:
MAE_mlp_reg = mean_absolute_error(y_test, y_pred_mlp)
MSE_mlp_reg = mean_squared_error(y_test, y_pred_mlp)
RMSE_mlp_reg = np.sqrt(MSE_mlp_reg)

metrics_mlp_reg = pd.DataFrame([MAE_mlp_reg, MSE_mlp_reg, RMSE_mlp_reg],
                               index=['MAE_mlp_reg', 'MSE_mlp_reg', 'RMSE_mlp_reg'],
                               columns=['Metrics'])

print("Evaluation Metrics for MLP Regressor:")
print(metrics_mlp_reg)

scores_mlp_reg = cross_val_score(mlp_reg_model, X_train_scaled, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation RMSE Scores:")
print(np.sqrt(-scores_mlp_reg))

r2_mlp_reg = r2_score(y_test, y_pred_mlp)
print("R-squared score:", r2_mlp_reg)

Evaluation Metrics for MLP Regressor:
                   Metrics
MAE_mlp_reg   1.255025e+04
MSE_mlp_reg   2.938602e+08
RMSE_mlp_reg  1.714235e+04
Cross-Validation RMSE Scores:
[17168.84474787 17041.67077343 19370.50183615 18396.6791381
 17746.7079636 ]
R-squared score: -1.0918717945708512


In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd

mlp_reg_model = MLPRegressor(hidden_layer_sizes=(100, 50), activation='relu', solver='adam', random_state=42)

mlp_reg_model.fit(X_train_scaled, y_train)

y_pred_mlp = mlp_reg_model.predict(X_test_scaled)

MAE_mlp_reg = mean_absolute_error(y_test, y_pred_mlp)
MSE_mlp_reg = mean_squared_error(y_test, y_pred_mlp)
RMSE_mlp_reg = np.sqrt(MSE_mlp_reg)
r2_mlp_reg = r2_score(y_test, y_pred_mlp)

print("Evaluation Metrics for MLP Regressor:")
print("MAE:", MAE_mlp_reg)
print("MSE:", MSE_mlp_reg)
print("RMSE:", RMSE_mlp_reg)
print("R-squared score:", r2_mlp_reg)

scores_mlp_reg = cross_val_score(mlp_reg_model, X_train_scaled, y_train, cv=5, scoring='neg_mean_squared_error')
print("Cross-Validation RMSE Scores:")
print(np.sqrt(-scores_mlp_reg))


Evaluation Metrics for MLP Regressor:
MAE: 4287.75273695574
MSE: 39925325.836424015
RMSE: 6318.649051531824
R-squared score: 0.7157878053864326
Cross-Validation RMSE Scores:
[6849.48983979 8137.86372953 9408.60437645 7835.25036552 8509.6937565 ]


# CatBoost Regression

In [ ]:

!pip install catboost
from catboost import CatBoostRegressor

cat_reg_model = CatBoostRegressor(random_state=42)

cat_reg_model.fit(X_train_scaled, y_train)


Learning rate set to 0.040517
0:	learn: 11841.1472117	total: 929us	remaining: 928ms
1:	learn: 11494.4901114	total: 2ms	remaining: 996ms
2:	learn: 11148.0587171	total: 3.65ms	remaining: 1.21s
3:	learn: 10837.3853223	total: 4.44ms	remaining: 1.11s
4:	learn: 10561.4791540	total: 5.35ms	remaining: 1.06s
5:	learn: 10260.1133264	total: 6.16ms	remaining: 1.02s
6:	learn: 9976.6752823	total: 7.02ms	remaining: 996ms
7:	learn: 9702.2782990	total: 7.92ms	remaining: 982ms
8:	learn: 9439.3669799	total: 8.76ms	remaining: 965ms
9:	learn: 9195.1059498	total: 9.35ms	remaining: 926ms
10:	learn: 8973.7282125	total: 10.6ms	remaining: 950ms
11:	learn: 8734.3641507	total: 11.5ms	remaining: 946ms
12:	learn: 8512.3834736	total: 12.4ms	remaining: 944ms
13:	learn: 8304.7923180	total: 13.3ms	remaining: 936ms
14:	learn: 8096.7513151	total: 14.2ms	remaining: 932ms
15:	learn: 7944.6905297	total: 14.7ms	remaining: 903ms
16:	learn: 7760.7422284	total: 15.6ms	remaining: 904ms
17:	learn: 7586.9047449	total: 16.3ms	remai

In [ ]:
y_pred = cat_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)


In [ ]:
MAE_cat_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_cat_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_cat_reg =np.sqrt(MSE_cat_reg)
pd.DataFrame([MAE_cat_reg, MSE_cat_reg, RMSE_cat_reg], index=['MAE_cat_reg', 'MSE_cat_reg', 'RMSE_cat_reg'], columns=['Metrics'])

Metrics
MAE_cat_reg   2.767633e+03
MSE_cat_reg   2.378685e+07
RMSE_cat_reg  4.877176e+03

In [ ]:
scores = cross_val_score(cat_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

Streaming output truncated to the last 5000 lines.
5:	learn: 10404.9346680	total: 29.6ms	remaining: 4.9s
6:	learn: 10132.3707999	total: 30.6ms	remaining: 4.34s
7:	learn: 9883.5885239	total: 39.7ms	remaining: 4.93s
8:	learn: 9630.2427553	total: 41.2ms	remaining: 4.53s
9:	learn: 9391.5934728	total: 41.7ms	remaining: 4.13s
10:	learn: 9193.8669223	total: 42.5ms	remaining: 3.82s
11:	learn: 8962.0173618	total: 47.1ms	remaining: 3.88s
12:	learn: 8746.6583619	total: 49.1ms	remaining: 3.73s
13:	learn: 8546.7379436	total: 51.8ms	remaining: 3.65s
14:	learn: 8361.8561262	total: 56.8ms	remaining: 3.73s
15:	learn: 8211.3981648	total: 57.4ms	remaining: 3.53s
16:	learn: 8033.8146547	total: 65.1ms	remaining: 3.76s
17:	learn: 7864.4408160	total: 65.9ms	remaining: 3.59s
18:	learn: 7697.0617892	total: 67.2ms	remaining: 3.47s
19:	learn: 7547.9270192	total: 71ms	remaining: 3.48s
20:	learn: 7397.2696078	total: 73.3ms	remaining: 3.42s
21:	learn: 7267.0877085	total: 78.1ms	remaining: 3.47s
22:	learn: 7122.8727

In [ ]:
r2_score(y_test, cat_reg_model.predict(X_test_scaled))

0.8306710953653351

# Huber Regressor

In [ ]:

from sklearn.linear_model import HuberRegressor

huber_reg_model = HuberRegressor()
huber_reg_model.fit(X_train_scaled, y_train)


HuberRegressor()

In [ ]:
y_pred = huber_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_huber_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_huber_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_huber_reg =np.sqrt(MSE_huber_reg)
pd.DataFrame([MAE_huber_reg, MSE_huber_reg, RMSE_huber_reg], index=['MAE_huber_reg', 'MSE_huber_reg', 'RMSE_huber_reg'], columns=['Metrics'])

Metrics
MAE_huber_reg   2.953231e+03
MSE_huber_reg   3.866109e+07
RMSE_huber_reg  6.217804e+03

In [ ]:
scores = cross_val_score(huber_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.84405615 0.8060616  0.80818189 0.82158808 0.77469955]


In [ ]:
r2_score(y_test, huber_reg_model.predict(X_test_scaled))

0.7247874130898331

# Light Gradient Boosting Machine

> Add blockquote



In [ ]:

import lightgbm as lgb

lgb_reg_model = lgb.LGBMRegressor(random_state=42)

lgb_reg_model.fit(X_train_scaled, y_train)


[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000421 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 321
[LightGBM] [Info] Number of data points in the train set: 936, number of used features: 6
[LightGBM] [Info] Start training from score 13463.722542


LGBMRegressor(random_state=42)

In [ ]:
y_pred = lgb_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_lgb_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_lgb_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_lgb_reg =np.sqrt(MSE_lgb_reg)
pd.DataFrame([MAE_lgb_reg, MSE_lgb_reg, RMSE_lgb_reg], index=['MAE_lgb_reg', 'MSE_lgb_reg', 'RMSE_lgb_reg'], columns=['Metrics'])

Metrics
MAE_lgb_reg   2.872124e+03
MSE_lgb_reg   2.417650e+07
RMSE_lgb_reg  4.916961e+03

In [ ]:
scores = cross_val_score(lgb_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000040 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 311
[LightGBM] [Info] Number of data points in the train set: 748, number of used features: 6
[LightGBM] [Info] Start training from score 13668.696329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

In [ ]:
r2_score(y_test, lgb_reg_model.predict(X_test_scaled))

0.8278972956552948

# Bayesian Ridge **Regressor**

In [ ]:

from sklearn.linear_model import BayesianRidge

bayesian_reg_model = BayesianRidge()

bayesian_reg_model.fit(X_train_scaled, y_train)


BayesianRidge()

In [ ]:
y_pred = bayesian_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_bayesian_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_bayesian_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_bayesian_reg =np.sqrt(MSE_bayesian_reg)
pd.DataFrame([MAE_bayesian_reg, MSE_bayesian_reg, RMSE_bayesian_reg], index=['MAE_bayesian_reg', 'MSE_bayesian_reg', 'RMSE_bayesian_reg'], columns=['Metrics'])

Metrics
MAE_bayesian_reg   3.993719e+03
MSE_bayesian_reg   3.355536e+07
RMSE_bayesian_reg  5.792699e+03

In [ ]:
scores = cross_val_score(bayesian_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.88788039 0.85654165 0.84399707 0.87194725 0.84428607]


In [ ]:
r2_score(y_test, bayesian_reg_model.predict(X_test_scaled))

0.7611329772340062

# Lasso Regression


In [ ]:
from sklearn.linear_model import Lasso
lasso_reg_model = Lasso(alpha=0.05, random_state=90)

lasso_reg_model.fit(X_train_scaled, y_train)


Lasso(alpha=0.05, random_state=90)

In [ ]:
y_pred = lasso_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_lasso_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_lasso_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_lasso_reg =np.sqrt(MSE_lasso_reg)
pd.DataFrame([MAE_lasso_reg, MSE_lasso_reg, RMSE_lasso_reg], index=['MAE_lasso_reg', 'MSE_lasso_reg', 'RMSE_lasso_reg'], columns=['Metrics'])

Metrics
MAE_lasso_reg   3.990249e+03
MSE_lasso_reg   3.353015e+07
RMSE_lasso_reg  5.790522e+03

In [ ]:
scores = cross_val_score(lasso_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.887914   0.85653092 0.84404188 0.87198371 0.84417531]


In [ ]:
r2_score(y_test, lasso_reg_model.predict(X_test_scaled))

0.7613124772957979

# Least Angle Regression

In [ ]:
from sklearn.linear_model import Lars
lars_reg_model = Lars(n_nonzero_coefs=1)

lars_reg_model.fit(X_train_scaled, y_train)


Lars(n_nonzero_coefs=1)

In [ ]:
y_pred = lars_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_lars_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_lars_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_lars_reg =np.sqrt(MSE_lars_reg)
pd.DataFrame([MAE_lars_reg, MSE_lars_reg, RMSE_lars_reg], index=['MAE_lars_reg', 'MSE_lars_reg', 'RMSE_lars_reg'], columns=['Metrics'])

Metrics
MAE_lars_reg   6.187347e+03
MSE_lars_reg   6.794253e+07
RMSE_lars_reg  8.242726e+03

In [ ]:
scores = cross_val_score(lars_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.741348   0.7284067  0.71678763 0.72873124 0.73358299]


In [ ]:
r2_score(y_test, lars_reg_model.predict(X_test_scaled))

0.5163446794045099

# AdaBoost Regressor

In [ ]:
from sklearn.ensemble import AdaBoostRegressor

ada_reg_model =AdaBoostRegressor(random_state=42, learning_rate=0.01)
ada_reg_model.fit(X_train_scaled, y_train)


AdaBoostRegressor(learning_rate=0.01, random_state=42)

In [ ]:
y_pred = ada_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_ada_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_ada_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_ada_reg =np.sqrt(MSE_ada_reg)
pd.DataFrame([MAE_ada_reg, MSE_ada_reg, RMSE_ada_reg], index=['MAE_ada_reg', 'MSE_ada_reg', 'RMSE_ada_reg'], columns=['Metrics'])

Metrics
MAE_ada_reg   3.007376e+03
MSE_ada_reg   2.266632e+07
RMSE_ada_reg  4.760916e+03

In [ ]:
scores = cross_val_score(ada_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.94529202 0.90773528 0.91442819 0.92973771 0.91062266]


In [ ]:
r2_score(y_test, ada_reg_model.predict(X_test_scaled))

0.8386476521651605

# Orthogonal Matching Pursuit	Regressor


In [ ]:
from sklearn.linear_model import OrthogonalMatchingPursuit
orth_reg_model = OrthogonalMatchingPursuit(n_nonzero_coefs=1)
orth_reg_model.fit(X_train_scaled, y_train)


OrthogonalMatchingPursuit(n_nonzero_coefs=1)

In [ ]:
y_pred = orth_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_orth_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_orth_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_orth_reg =np.sqrt(MSE_orth_reg)
pd.DataFrame([MAE_orth_reg, MSE_orth_reg, RMSE_orth_reg], index=['MAE_orth_reg', 'MSE_orth_reg', 'RMSE_orth_reg'], columns=['Metrics'])

Metrics
MAE_orth_reg   5.513935e+03
MSE_orth_reg   5.447327e+07
RMSE_orth_reg  7.380601e+03

In [ ]:
scores = cross_val_score(orth_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.80064687 0.7738914  0.78738299 0.79020527 0.78286924]


In [ ]:
r2_score(y_test, orth_reg_model.predict(X_test_scaled))

0.6122268811542722

# Elastic Net Regressor

In [ ]:
from sklearn.linear_model import ElasticNet

elastic_reg_model = ElasticNet(alpha=0.05, l1_ratio=0.5, random_state=42)

elastic_reg_model.fit(X_train_scaled, y_train)


ElasticNet(alpha=0.05, random_state=42)

In [ ]:
y_pred = elastic_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_elastic_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_elastic_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_elastic_reg =np.sqrt(MSE_elastic_reg)
pd.DataFrame([MAE_elastic_reg, MSE_elastic_reg, RMSE_elastic_reg], index=['MAE_elastic_reg', 'MSE_elastic_reg', 'RMSE_elastic_reg'], columns=['Metrics'])

Metrics
MAE_elastic_reg   4.032087e+03
MSE_elastic_reg   3.385831e+07
RMSE_elastic_reg  5.818789e+03

In [ ]:
scores = cross_val_score(elastic_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.88740559 0.85640921 0.84339717 0.87143716 0.84493835]


In [ ]:
r2_score(y_test, elastic_reg_model.predict(X_test_scaled))

0.7589764531451498

# Ridge Regressor

In [ ]:
from sklearn.linear_model import Ridge

ridge_reg_model = Ridge(alpha=0.05, random_state=42)
ridge_reg_model.fit(X_train_scaled, y_train)


Ridge(alpha=0.05, random_state=42)

In [ ]:
y_pred = ridge_reg_model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred)

In [ ]:
MAE_ridge_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_ridge_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_ridge_reg =np.sqrt(MSE_ridge_reg)
pd.DataFrame([MAE_ridge_reg, MSE_ridge_reg, RMSE_ridge_reg], index=['MAE_ridge_reg', 'MSE_ridge_reg', 'RMSE_ridge_reg'], columns=['Metrics'])

Metrics
MAE_ridge_reg   3.990332e+03
MSE_ridge_reg   3.353073e+07
RMSE_ridge_reg  5.790572e+03

In [ ]:
scores = cross_val_score(ridge_reg_model, X_train_scaled, y_train, cv=5)
print(np.sqrt(scores))

[0.88791321 0.85653082 0.84404088 0.87198293 0.84417776]


In [ ]:
r2_score(y_test, ridge_reg_model.predict(X_test_scaled))

0.7613083624094129

# OLC Regression

In [ ]:
lm=sm.OLS(y_train,X_train)
model=lm.fit()
model.summary()


NameError: name 'sm' is not defined

# SVR

In [ ]:
from sklearn.svm import SVR

svr_reg = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=0.1)



In [ ]:
svr_reg= metrics.mean_absolute_error(y_test, y_pred)
MSE_svr_reg = metrics.mean_squared_error(y_test, y_pred)
RMSE_svr_reg =np.sqrt(MSE_svr_reg)
pd.DataFrame([svr_reg, MSE_svr_reg, RMSE_svr_reg], index=['svr_reg', 'MSE_svr_reg', 'RMSE_svr_reg'], columns=['Metrics'])

Metrics
svr_reg       3.990332e+03
MSE_svr_reg   3.353073e+07
RMSE_svr_reg  5.790572e+03

In [ ]:
scores = cross_val_score(svr_reg, X_train_scaled, y_train, cv=5)

print(np.sqrt(scores))

TypeError: estimator should be an estimator implementing 'fit' method, 3990.332292888588 was passed

In [ ]:
print(type(svr_reg))

<class 'numpy.float64'>


In [ ]:
hasattr(svr_reg, 'fit')

False